# Generated by Django 3.0 on 2020-07-15 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='foods',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='state',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.CartOrder'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Recipe'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('FAILURE', 'Failure')], default='PENDING', max_length=32),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orders.Payments'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='gateway',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('STRIPE', 'Stripe')], default='Credit', max_length=48, null=True),
        ),
        migrations.DeleteModel(
            name='PaymentState',
        ),
    ]
