# Generated by Django 3.0.7 on 2020-07-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200626_1232'),
        ('orders', '0002_auto_20200618_1616'),
    ]

    operations = [
    ]
